/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.controladorAprendices;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modelo.Aprendices;

/**
 *
 * @author CGAO
 */
public class FRMAprendices extends javax.swing.JInternalFrame {

    controladorAprendices aprendizController = new controladorAprendices();
    
    public FRMAprendices() {
        initComponents();
        idAprendices.setValue(0);
        idAprendices.setVisible(false);
        limpiarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idAprendices = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNombreA = new javax.swing.JTextField();
        tFichaA = new javax.swing.JTextField();
        tIdent = new javax.swing.JTextField();
        bInsertar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAprendices = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Aprendices");

        idAprendices.setText("0");
        idAprendices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAprendicesActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Ficha:");

        jLabel3.setText("Ident:");

        tNombreA.setText("Nombre");

        tFichaA.setText("Ficha");

        tIdent.setText("Ident");

        bInsertar.setText("Insertar");
        bInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        taAprendices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idAprenedices", "Nombre", "Ficha", "Ident"
            }
        ));
        taAprendices.setEnabled(false);
        taAprendices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taAprendicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taAprendices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idAprendices, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bInsertar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tFichaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bEliminar, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(7, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idAprendices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInsertar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tFichaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bModificar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tIdent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idAprendicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAprendicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAprendicesActionPerformed

    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarActionPerformed
        aprendizController.controlarAprendices(evt, obtenerAprendices());
        limpiarFormulario();
    }//GEN-LAST:event_bInsertarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        aprendizController.controlarAprendices(evt, obtenerAprendices());
        limpiarFormulario();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        aprendizController.controlarAprendices(evt, obtenerAprendices());
        limpiarFormulario();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void taAprendicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taAprendicesMouseClicked
         if (evt.getClickCount()==2) {
            int fila = taAprendices.rowAtPoint(evt.getPoint());
            if (fila>-1) {
                idAprendices.setValue((Integer)taAprendices.getValueAt(fila, 0));
                tNombreA.setText((String)taAprendices.getValueAt(fila, 1));
                tFichaA.setText((String)taAprendices.getValueAt(fila, 2));
                tIdent.setText((String)taAprendices.getValueAt(fila, 3));
                bModificar.setEnabled(true);
                bEliminar.setEnabled(true);
            }
        }

    }//GEN-LAST:event_taAprendicesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bInsertar;
    private javax.swing.JButton bModificar;
    private javax.swing.JFormattedTextField idAprendices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFichaA;
    private javax.swing.JTextField tIdent;
    private javax.swing.JTextField tNombreA;
    private javax.swing.JTable taAprendices;
    // End of variables declaration//GEN-END:variables
    private void limpiarFormulario(){
        idAprendices.setValue(0);
        tNombreA.setText("Ingrese N");
        tFichaA.setText("Ingrese F");
        tIdent.setText("Ingrese I");
        bModificar.setEnabled(false);
        bEliminar.setEnabled(false);
        llenarTabla();
    }
    
    public void llenarTabla(){
        Aprendices unAprendices = new Aprendices();
        DefaultTableModel tabla = (DefaultTableModel)taAprendices.getModel();
        Iterator<Aprendices> itAprendices = unAprendices.listar();
        Object[] filaAprendices = new Object[taAprendices.getColumnCount()];
        tabla.setRowCount(0);
        while (itAprendices.hasNext()) {
            unAprendices = itAprendices.next();
            filaAprendices[0] = unAprendices.getIdAprendices();
            filaAprendices[1] = unAprendices.getNombreA();
            filaAprendices[2] = unAprendices.getFichaA();
            filaAprendices[3] = unAprendices.getIdent();
            tabla.addRow(filaAprendices);
        }
    }
    private Aprendices obtenerAprendices(){
        Aprendices elAprendices = new Aprendices();
        elAprendices.setIdAprendices((Integer) idAprendices.getValue());
        elAprendices.setNombreA(tNombreA.getText());
        elAprendices.setFichaA(tFichaA.getText());
        elAprendices.setIdent(tIdent.getText());
        return elAprendices;
    }
}
