/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.controladorEntrada;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import modelo.Entrada;

/**
 *
 * @author gutie
 */
public class FRMEntrada extends javax.swing.JInternalFrame {

    controladorEntrada clienteController = new controladorEntrada();
    
    public FRMEntrada() {
        initComponents();
        idEntrada.setValue(0);
        idEntrada.setVisible(false);
        limpiarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bInsertar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEntrada = new javax.swing.JTable();
        tBuscar = new javax.swing.JTextField();
        idEntrada = new javax.swing.JFormattedTextField();
        tCelador = new javax.swing.JSpinner();
        tAprendiz = new javax.swing.JSpinner();
        tPortatil = new javax.swing.JSpinner();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Entrada");

        bInsertar.setText("Insertar");
        bInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInsertarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Celador:");

        jLabel2.setText("Aprendiz:");

        jLabel3.setText("Portatil:");

        jLabel4.setText("Fecha:");

        tFecha.setText("ingrese d");
        tFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFechaActionPerformed(evt);
            }
        });

        taEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idEntrada", "idCelador", "idAprendiz", "idPortatil", "Fecha"
            }
        ));
        taEntrada.setEnabled(false);
        taEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taEntradaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taEntrada);

        tBuscar.setText("Buscar...");
        tBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tBuscarFocusLost(evt);
            }
        });

        idEntrada.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(bBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bInsertar)
                                            .addComponent(tCelador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bModificar)
                                            .addComponent(tAprendiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(bEliminar))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(idEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(idEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCelador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tAprendiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInsertar)
                    .addComponent(bModificar)
                    .addComponent(bEliminar))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuscar)
                    .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInsertarActionPerformed
        clienteController.controlarEntrada(evt, obtenerEntrada());
        limpiarFormulario();
    }//GEN-LAST:event_bInsertarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        clienteController.controlarEntrada(evt, obtenerEntrada());
        limpiarFormulario();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        clienteController.controlarEntrada(evt, obtenerEntrada());
        limpiarFormulario();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void taEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taEntradaMouseClicked
        if (evt.getClickCount()==2) {
            int fila = taEntrada.rowAtPoint(evt.getPoint());
            if (fila>-1) {
                idEntrada.setValue((Integer)taEntrada.getValueAt(fila, 0));
                tCelador.setValue((Integer)taEntrada.getValueAt(fila, 1));
                tAprendiz.setValue((Integer)taEntrada.getValueAt(fila, 2));
                tPortatil.setValue((Integer)taEntrada.getValueAt(fila, 3));
                tFecha.setText((String)taEntrada.getValueAt(fila, 4));
                bModificar.setEnabled(true);
                bEliminar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_taEntradaMouseClicked

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        llenarTablaConBusqueda(tBuscar.getText());
    }//GEN-LAST:event_bBuscarActionPerformed

    private void tBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBuscarFocusGained
        if (tBuscar.getText().equals("Escriba para buscar")) {
        }
    }//GEN-LAST:event_tBuscarFocusGained

    private void tBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBuscarFocusLost
        if (tBuscar.getText().isEmpty()) {
        }
    }//GEN-LAST:event_tBuscarFocusLost

    private void tFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bInsertar;
    private javax.swing.JButton bModificar;
    private javax.swing.JFormattedTextField idEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner tAprendiz;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JSpinner tCelador;
    private javax.swing.JTextField tFecha;
    private javax.swing.JSpinner tPortatil;
    private javax.swing.JTable taEntrada;
    // End of variables declaration//GEN-END:variables
    
    private void limpiarFormulario(){
        idEntrada.setValue(0);
        tCelador.setValue(0);
        tAprendiz.setValue(0);
        tPortatil.setValue(0);
        tFecha.setText("Ingrese d");
        bModificar.setEnabled(false);
        bEliminar.setEnabled(false);
        llenarTabla();
    }
    
    public void llenarTabla(){
        Entrada unEntrada = new Entrada();
        DefaultTableModel tabla = (DefaultTableModel)taEntrada.getModel();
        Iterator<Entrada> itEntrada = unEntrada.listar();
        Object[] filaEntrada = new Object[taEntrada.getColumnCount()];
        tabla.setRowCount(0);
        while (itEntrada.hasNext()) {
            unEntrada = itEntrada.next();
            filaEntrada[0] = unEntrada.getIdEntrada();
            filaEntrada[1] = unEntrada.getIdCelador();
            filaEntrada[2] = unEntrada.getIdAprendices();
            filaEntrada[3] = unEntrada.getIdPortatil();
            filaEntrada[4] = unEntrada.getFechaEntrada();
            tabla.addRow(filaEntrada);
        }
    }
    
    private Entrada obtenerEntrada(){
        Entrada elEntrada = new Entrada();
        elEntrada.setIdEntrada((Integer) idEntrada.getValue());
        elEntrada.setIdCelador((Integer) tCelador.getValue());
        elEntrada.setIdAprendices((Integer) tAprendiz.getValue());
        elEntrada.setIdPortatil((Integer) tPortatil.getValue());
        elEntrada.setFechaEntrada(tFecha.getText());
        return elEntrada;
    }
    
    private void llenarTablaConBusqueda(String busqueda){
        Entrada unEntrada = new Entrada();
        DefaultTableModel tabla = (DefaultTableModel)taEntrada.getModel();
        Iterator<Entrada> itEntrada = unEntrada.buscar(busqueda);
        Object[] filaEntrada = new Object[taEntrada.getColumnCount()];
        tabla.setRowCount(0);
        while (itEntrada.hasNext()) {            
            unEntrada = itEntrada.next();
            filaEntrada[0] = unEntrada.getIdEntrada();
            filaEntrada[1] = unEntrada.getIdCelador();
            filaEntrada[2] = unEntrada.getIdAprendices();
            filaEntrada[3] = unEntrada.getIdPortatil();
            filaEntrada[4] = unEntrada.getFechaEntrada();
            ((DefaultTableModel)taEntrada.getModel()).addRow(filaEntrada);
        }
    }
}
